CREATE TABLE IF NOT EXISTS weather_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(120) NOT NULL,
    country VARCHAR(80),
    country_code VARCHAR(8),
    region VARCHAR(120),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    timezone VARCHAR(80),
    temperature DOUBLE PRECISION,
    temperature_unit VARCHAR(20),
    apparent_temperature DOUBLE PRECISION,
    humidity INTEGER,
    humidity_unit VARCHAR(20),
    wind_speed DOUBLE PRECISION,
    wind_speed_unit VARCHAR(20),
    weather_code INTEGER,
    weather_time VARCHAR(40),
    consulted_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_weather_query_city ON weather_query (city);
CREATE INDEX IF NOT EXISTS idx_weather_query_country ON weather_query (country);
CREATE INDEX IF NOT EXISTS idx_weather_query_consulted_at ON weather_query (consulted_at);
